Install deps for web
Exec:
```
npx expo install react-native-web@~0.18.10 react-dom@18.2.0 @expo/webpack-config@^18.0.1
```

Got the following error:
```
npm run web

> rosenkoenig-web@1.0.0 web
> expo start --web

Starting project at /path/to/rosenkoenig-web
CommandError: It looks like you're trying to use web support but don't have the required dependencies
installed.

Please install react-native-web@~0.18.10, react-dom@18.2.0, @expo/webpack-config@^18.0.1 by
running:

npx expo install react-native-web@~0.18.10 react-dom@18.2.0 @expo/webpack-config@^18.0.1

If you're not using web, please ensure you remove the "web" string from the platforms array in
the project Expo config.
```